name: Docker Hub

on:
  push:
    branches:
      - develop

jobs:
  docker-hub:
    name: Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image
        run: make build env=ci
        working-directory: api
      - name: Push to Docker Hub
        run: make push env=ci
        working-directory: api
