name: Expo
on:
  push:
    branches:
      - develop
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Run Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: mobile/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
        working-directory: mobile
      - name: Setup Expo CLI
        uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-cache: true
      - name: Publish Build
        run: expo build:ios --no-wait --type simulator
        working-directory: mobile
