name: Tests
on:
  push:
jobs:
  api:
    name: API
    runs-on: ubuntu-latest
    steps:
      - name: Run Checkout
        uses: actions/checkout@v2
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock')}}
          restore-keys: ${{ runner.os }}-yarn-
        working-directory: api
      - name: Setup Node
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
        working-directory: api
      - name: Run Eslint
        run: npm run eslint
        working-directory: api
      - name: Run Prettier
        run: npm run prettier
        working-directory: api
  mobile:
    name: Mobile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock')}}
          restore-keys: ${{ runner.os }}-yarn-
        working-directory: mobile
      - name: Setup Node
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
        working-directory: mobile
      - name: Run Eslint
        run: npm run eslint
        working-directory: mobile
      - name: Run Prettier
        run: npm run prettier
        working-directory: mobile
